// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myvccimnexoufkdzspvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15dmNjaW1uZXhvdWZrZHpzcHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzQwNjMsImV4cCI6MjA2NjM1MDA2M30._Qr6MfoPNiHgBWNzme_5WXCoZDzlfWkmQ25Tr7RJoMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});